import type {
  ReportBusiness,
  ReportDocument,
  ReportKpiSection,
  ReportKeyValueSection,
  ReportNoteSection,
  ReportSection,
  ReportTableSection,
} from '@biztrack/types'
import { escapeHtml } from './format'

export interface ReportLabels {
  generated: string
  generatedBy: string
  amountsIn: string
}

export function reportLabels(locale: string): ReportLabels {
  const fr = (locale || 'fr').toLowerCase().startsWith('fr')
  return fr
    ? { generated: 'Généré le', generatedBy: 'Généré par BizTrack CM', amountsIn: 'Montants en' }
    : { generated: 'Generated', generatedBy: 'Generated by BizTrack CM', amountsIn: 'Amounts in' }
}

// Statutory-grade "paper" (A4) with a fixed ink palette so print is stable regardless
// of the app theme. Mirrors the approved report document design (letterhead + section
// headers + fin tables + KPI strip + notes + footer). Self-contained — inlined into the
// document, shown on screen in an iframe AND compiled to PDF by the backend.
const REPORT_DOC_CSS = `
  *{box-sizing:border-box;}
  html,body{margin:0;padding:0;}
  body{background:#eef1f5;font-family:-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    display:flex;justify-content:center;padding:20px;-webkit-print-color-adjust:exact;print-color-adjust:exact;}
  .paper{--ink:#161b22;--ink2:#3d4653;--mut:#6b7482;--rule:#d7dce4;--rule2:#eef1f5;--fill:#f5f7fa;
    --accent:#16467A;--accent-soft:#eaf0f8;--ok:#1f8a5b;--warn:#b06a00;--danger:#c0392b;
    width:210mm;min-height:297mm;background:#fff;color:var(--ink);
    box-shadow:0 4px 24px -6px rgba(20,30,50,.28),0 2px 8px -2px rgba(20,30,50,.16);
    padding:15mm 16mm 14mm;font-size:10.5px;line-height:1.5;position:relative;}
  .paper .amt{font-variant-numeric:tabular-nums;text-align:right;white-space:nowrap;}
  .paper .neg,.paper .down{color:var(--danger);}
  .paper .up{color:var(--ok);} .paper .warn{color:var(--warn);}

  .doc-head{display:flex;gap:14px;align-items:flex-start;padding-bottom:12px;border-bottom:2px solid var(--accent);}
  .doc-logo{width:52px;height:52px;border-radius:11px;background:var(--accent);color:#fff;display:grid;place-items:center;font-size:19px;font-weight:800;letter-spacing:-.5px;flex-shrink:0;overflow:hidden;}
  .doc-logo img{width:100%;height:100%;object-fit:cover;}
  .doc-entity{flex:1;min-width:0;}
  .doc-entity .nm{font-size:16px;font-weight:800;letter-spacing:-.3px;}
  .doc-entity .form{font-size:10px;color:var(--accent);font-weight:700;text-transform:uppercase;letter-spacing:.05em;margin-top:1px;}
  .doc-entity .act{font-size:10px;color:var(--ink2);margin-top:3px;}
  .doc-entity .addr{font-size:9.5px;color:var(--mut);margin-top:3px;line-height:1.45;}
  .doc-ids{flex-shrink:0;width:52mm;font-size:9px;line-height:1.5;}
  .doc-ids .row{display:flex;justify-content:space-between;gap:8px;padding:1.5px 0;border-bottom:1px dotted var(--rule);}
  .doc-ids .row:last-child{border-bottom:0;}
  .doc-ids .k{color:var(--mut);text-transform:uppercase;letter-spacing:.04em;font-size:8px;font-weight:600;}
  .doc-ids .v{color:var(--ink);font-weight:700;text-align:right;font-variant-numeric:tabular-nums;}

  .doc-title{margin:14px 0 4px;text-align:center;}
  .doc-title h1{font-size:16px;font-weight:800;letter-spacing:.02em;text-transform:uppercase;margin:0;}
  .doc-title .fr{font-size:11px;font-weight:600;color:var(--accent);margin-top:2px;font-style:italic;}
  .doc-title .per{font-size:10px;color:var(--ink2);margin-top:6px;}
  .doc-title .per b{color:var(--ink);}
  .doc-meta-row{display:flex;justify-content:space-between;align-items:flex-end;font-size:9px;color:var(--mut);margin-top:8px;padding-bottom:4px;border-bottom:1px solid var(--rule);}
  .doc-meta-row .unit{font-weight:700;color:var(--ink2);text-transform:uppercase;letter-spacing:.05em;}

  .doc-sec{margin-top:14px;}
  .doc-sec-h{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.06em;color:#fff;background:var(--accent);padding:4px 9px;border-radius:4px;display:flex;justify-content:space-between;align-items:center;}
  .doc-sec-h .frn{font-weight:500;font-style:italic;text-transform:none;letter-spacing:0;opacity:.85;font-size:9px;}

  table.fin{width:100%;border-collapse:collapse;margin-top:6px;}
  table.fin th{font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:var(--mut);padding:5px 7px;border-bottom:1.5px solid var(--ink2);text-align:right;vertical-align:bottom;}
  table.fin th.l{text-align:left;}
  table.fin td{padding:3.5px 7px;border-bottom:1px solid var(--rule2);vertical-align:top;}
  table.fin td.lib{color:var(--ink2);}
  table.fin td.lib .frn{color:var(--mut);font-style:italic;font-size:9px;}
  table.fin td.num{width:30mm;}
  table.fin tr.sub td.lib{padding-left:16px;}
  table.fin tr.grp td{background:var(--fill);font-weight:800;text-transform:uppercase;font-size:8.5px;letter-spacing:.04em;color:var(--ink);border-bottom:1px solid var(--rule);}
  table.fin tr.tot td{font-weight:800;border-top:1.5px solid var(--ink2);border-bottom:1.5px solid var(--ink2);color:var(--ink);background:#fbfcfd;}
  table.fin tr.grand td{font-weight:800;font-size:11px;border-top:2px solid var(--accent);border-bottom:3px double var(--accent);color:var(--ink);background:var(--accent-soft);}
  .doc-pill{display:inline-block;font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;padding:2px 7px;border-radius:5px;}
  .doc-pill.pos{background:#e7f6ee;color:var(--ok);} .doc-pill.neg{background:#fbeae7;color:var(--danger);}
  .chk{font-size:9px;color:var(--ok);font-weight:700;text-align:center;margin-top:5px;} .chk.bad{color:var(--danger);}

  .doc-kpis{display:grid;gap:8px;margin-top:12px;}
  .doc-kpi{border:1px solid var(--rule);border-radius:7px;padding:8px 10px;}
  .doc-kpi .k{font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:var(--mut);}
  .doc-kpi .v{font-size:14px;font-weight:800;margin-top:3px;font-variant-numeric:tabular-nums;}
  .doc-kpi .h{font-size:8.5px;color:var(--mut);margin-top:1px;}

  .doc-note{font-size:9px;color:var(--ink2);background:var(--accent-soft);border-left:3px solid var(--accent);padding:7px 10px;border-radius:0 5px 5px 0;margin-top:10px;line-height:1.5;}
  .doc-foot{margin-top:16px;padding-top:8px;border-top:1px solid var(--rule);display:flex;justify-content:space-between;align-items:center;font-size:8px;color:var(--mut);gap:10px;}
  .doc-foot .brand{display:inline-flex;align-items:center;gap:5px;font-weight:700;color:var(--ink2);}
  .doc-foot .brand i{width:12px;height:12px;border-radius:3px;background:var(--accent);color:#fff;display:inline-grid;place-items:center;font-size:7px;font-weight:800;font-style:normal;}

  @page{size:A4;margin:0;}
  @media print{body{background:#fff;padding:0;display:block;}.paper{box-shadow:none;width:210mm;}}
`

function initials(name: string): string {
  const p = name.trim().split(/\s+/).filter(Boolean)
  if (!p.length) return 'B'
  return ((p[0]![0] ?? '') + (p.length > 1 ? p[p.length - 1]![0] ?? '' : '')).toUpperCase()
}

function renderLetterhead(b: ReportBusiness): string {
  const logo = b.logoUrl
    ? `<div class="doc-logo"><img src="${escapeHtml(b.logoUrl)}" alt="" /></div>`
    : `<div class="doc-logo">${escapeHtml(initials(b.name))}</div>`
  const loc = [b.address, b.city].filter(Boolean).map((s) => escapeHtml(s as string)).join(' · ')
  const contact = [b.phone, b.email].filter(Boolean).map((s) => escapeHtml(s as string)).join(' · ')
  const addr = loc || contact ? `<div class="addr">${loc}${loc && contact ? '<br>' : ''}${contact}</div>` : ''
  const ids: Array<[string, string | null | undefined]> = [
    ['NIU', b.taxId],
    ['RCCM', b.registration],
    ['Régime', b.taxRegime],
    ['Capital', b.capital],
  ]
  const idRows = ids
    .filter(([, v]) => !!v)
    .map(([k, v]) => `<div class="row"><span class="k">${escapeHtml(k)}</span><span class="v">${escapeHtml(v as string)}</span></div>`)
    .join('')
  const idsBlock = idRows ? `<div class="doc-ids">${idRows}</div>` : ''
  return `<div class="doc-head">${logo}<div class="doc-entity">
      <div class="nm">${escapeHtml(b.name)}</div>
      ${b.type ? `<div class="form">${escapeHtml(b.type)}</div>` : ''}
      ${b.activity ? `<div class="act">${escapeHtml(b.activity)}</div>` : ''}
      ${addr}
    </div>${idsBlock}</div>`
}

function toneCls(tone?: string): string {
  return tone === 'up' ? ' up' : tone === 'down' ? ' down' : tone === 'warn' ? ' warn' : ''
}

function renderKpis(s: ReportKpiSection): string {
  const cols = Math.min(4, Math.max(1, s.items.length))
  const items = s.items
    .map(
      (k) => `<div class="doc-kpi"><div class="k">${escapeHtml(k.label)}</div>` +
        `<div class="v">${escapeHtml(k.value)}</div>` +
        `${k.hint ? `<div class="h${toneCls(k.tone)}">${escapeHtml(k.hint)}</div>` : ''}</div>`,
    )
    .join('')
  return `<div class="doc-kpis" style="grid-template-columns:repeat(${cols},1fr)">${items}</div>`
}

function cellClass(align?: string): string {
  return align === 'right' ? 'amt num' : 'lib'
}

function sectionHeader(title?: string, titleFr?: string): string {
  if (!title) return ''
  const fr = titleFr ? `<span class="frn">${escapeHtml(titleFr)}</span>` : ''
  return `<div class="doc-sec-h"><span>${escapeHtml(title)}</span>${fr}</div>`
}

function renderTable(s: ReportTableSection): string {
  const head = s.columns.map((c) => `<th class="${c.align === 'right' ? '' : 'l'}">${escapeHtml(c.label)}</th>`).join('')
  const body =
    s.rows.length === 0
      ? `<tr><td class="lib" colspan="${s.columns.length}" style="color:var(--mut)">${escapeHtml(s.empty ?? '—')}</td></tr>`
      : s.rows
          .map((row) => `<tr class="sub">${s.columns.map((c) => `<td class="${cellClass(c.align)}">${escapeHtml(row[c.key] ?? '')}</td>`).join('')}</tr>`)
          .join('')
  const total = s.total
    ? `<tr class="grand">${s.columns.map((c) => `<td class="${cellClass(c.align)}">${escapeHtml(s.total![c.key] ?? '')}</td>`).join('')}</tr>`
    : ''
  return `<div class="doc-sec">${sectionHeader(s.title, s.titleFr)}<table class="fin"><thead><tr>${head}</tr></thead><tbody>${body}${total}</tbody></table></div>`
}

function renderKeyValue(s: ReportKeyValueSection): string {
  const rows = s.rows
    .map(
      (r) => `<tr class="${r.strong ? 'grand' : r.subtotal ? 'tot' : 'sub'}"><td class="lib">${escapeHtml(r.label)}</td>` +
        `<td class="amt num${toneCls(r.tone)}">${escapeHtml(r.value)}</td></tr>`,
    )
    .join('')
  return `<div class="doc-sec">${sectionHeader(s.title, s.titleFr)}<table class="fin"><tbody>${rows}</tbody></table></div>`
}

function renderNote(s: ReportNoteSection): string {
  return `<div class="doc-note">${escapeHtml(s.text)}</div>`
}

function renderSection(s: ReportSection): string {
  switch (s.kind) {
    case 'kpis':
      return renderKpis(s)
    case 'table':
      return renderTable(s)
    case 'keyvalue':
      return renderKeyValue(s)
    case 'note':
      return renderNote(s)
  }
}

function stamp(iso: string, locale: string): string {
  try {
    return new Date(iso).toLocaleString(locale, { dateStyle: 'medium', timeStyle: 'short' })
  } catch {
    return iso
  }
}
function dateShort(iso: string, locale: string): string {
  try {
    return new Date(iso).toLocaleDateString(locale, { dateStyle: 'medium' })
  } catch {
    return iso
  }
}

/** Render a report as a self-contained statutory-style A4 HTML document (screen preview + PDF). */
export function renderReportDocumentHtml(doc: ReportDocument, opts: { labels: ReportLabels; locale?: string }): string {
  const L = opts.labels
  const locale = opts.locale ?? 'fr'
  const paper = `<div class="paper">
    ${renderLetterhead(doc.business)}
    <div class="doc-title">
      <h1>${escapeHtml(doc.title)}</h1>
      ${doc.subtitle ? `<div class="fr">${escapeHtml(doc.subtitle)}</div>` : ''}
      <div class="per"><b>${escapeHtml(doc.periodLabel)}</b></div>
    </div>
    <div class="doc-meta-row">
      <span>${escapeHtml(L.generated)} ${escapeHtml(stamp(doc.generatedAt, locale))}</span>
      ${doc.unit ? `<span class="unit">${escapeHtml(L.amountsIn)} ${escapeHtml(doc.unit)}</span>` : ''}
    </div>
    ${doc.sections.map(renderSection).join('')}
    <div class="doc-foot">
      <span class="brand"><i>B</i> ${escapeHtml(L.generatedBy)} · ${escapeHtml(dateShort(doc.generatedAt, locale))}</span>
      <span></span>
      <span>${escapeHtml(doc.business.name)}</span>
    </div>
  </div>`
  return `<!doctype html><html lang="${escapeHtml(locale)}"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${escapeHtml(doc.title)} · ${escapeHtml(doc.periodLabel)}</title><style>${REPORT_DOC_CSS}</style></head><body>${paper}</body></html>`
}
