import type { SaleReceipt } from '@biztrack/types'
import { escapeHtml, formatMoney } from './format'

/**
 * Translated strings the receipt needs. Passed in by the caller so the template stays
 * language-agnostic (desktop passes en/fr from its catalog; the API passes its own i18n).
 * `methods` maps a PaymentMethod value to its display label.
 */
export interface SaleReceiptLabels {
  subtotal: string
  discounts: string
  charges: string
  total: string
  paid: string
  credit: string
  change: string
  cashier: string
  customer: string
  thankYou: string
  /** Prefix before a discounted line's original price, e.g. "Prix 2 500 → 2 200". */
  priceWas: string
  methods: Record<string, string>
}

/** Built-in en/fr receipt labels so the API and desktop render identical receipts
 * without each re-deriving the strings. Callers may still pass their own labels. */
export function saleReceiptLabels(locale: string): SaleReceiptLabels {
  const fr = (locale || 'fr').toLowerCase().startsWith('fr')
  const methods = fr
    ? {
        CASH: 'Espèces',
        MTN_MOMO: 'MTN MoMo',
        ORANGE_MONEY: 'Orange Money',
        CARD: 'Carte',
        SAVINGS: 'Dépôt',
        MIXED: 'Partagé',
      }
    : {
        CASH: 'Cash',
        MTN_MOMO: 'MTN MoMo',
        ORANGE_MONEY: 'Orange Money',
        CARD: 'Card',
        SAVINGS: 'Deposit',
        MIXED: 'Split',
      }
  return fr
    ? {
        subtotal: 'Sous-total',
        discounts: 'Remises',
        charges: 'Frais',
        total: 'Total',
        paid: 'Payé',
        credit: 'Crédit',
        change: 'Monnaie rendue',
        cashier: 'Caissier',
        customer: 'Client',
        thankYou: 'Merci pour votre achat !',
        priceWas: 'Prix',
        methods,
      }
    : {
        subtotal: 'Subtotal',
        discounts: 'Discounts',
        charges: 'Charges',
        total: 'Total',
        paid: 'Paid',
        credit: 'Credit',
        change: 'Change given',
        cashier: 'Cashier',
        customer: 'Customer',
        thankYou: 'Thank you for your purchase!',
        priceWas: 'Price',
        methods,
      }
}

export interface SaleReceiptOptions {
  labels: SaleReceiptLabels
  /** Locale for money/date formatting (e.g. 'fr', 'en'). Defaults to 'fr'. */
  locale?: string
  /** Paper width in mm (thermal rolls are 58 or 80). Defaults to 58. */
  widthMm?: number
  /** Content toggles (from the business receipt settings). All default on. */
  showNiu?: boolean
  showCashier?: boolean
  showPayment?: boolean
  showThanks?: boolean
  showLogo?: boolean
  showQr?: boolean
  /** Pre-rendered QR as a data-URI (generated by the caller); shown when showQr + present. */
  qrImage?: string | null
}

const on = (v: boolean | undefined): boolean => v !== false

/**
 * Render a point-of-sale receipt as a self-contained thermal HTML document (design-receipts mock).
 * Shared by the desktop app (printed via printToPDF) and the API (PDF render + dispatch) so a
 * customer's receipt looks identical wherever it's produced, and matches the settings preview.
 */
export function renderSaleReceiptHtml(receipt: SaleReceipt, opts: SaleReceiptOptions): string {
  const L = opts.labels
  const locale = opts.locale ?? 'fr'
  const width = opts.widthMm ?? 58
  const currency = (receipt.currency as string) || 'XAF'
  const m = (n: number): string => formatMoney(n, currency, locale)
  const d = new Date(receipt.soldAt)
  const date = isNaN(d.getTime()) ? escapeHtml(receipt.soldAt) : d.toLocaleDateString(locale)
  const time = isNaN(d.getTime())
    ? ''
    : d.toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' })

  const line = (label: string, value: string, cls = ''): string =>
    `<div class="line ${cls}"><span>${escapeHtml(label)}</span><span>${escapeHtml(value)}</span></div>`

  const items = receipt.items
    .map((it) => {
      const listed = it.unitPriceListed ?? null
      const lineDiscount = it.discountAmount ?? 0
      const charged = it.qty > 0 && listed != null ? Math.round(listed - lineDiscount / it.qty) : 0
      const nm = `${escapeHtml(it.name)} ×${escapeHtml(formatQty(it.qty, locale))}`
      const sub =
        listed != null && lineDiscount > 0 && listed > charged
          ? `<div class="sub">${escapeHtml(`${L.priceWas} ${m(listed)} → ${m(charged)}`)}</div>`
          : ''
      return `<div class="line"><span class="nm">${nm}</span><span>${escapeHtml(m(it.total))}</span></div>${sub}`
    })
    .join('')

  const totalDiscounts =
    receipt.discountAmount + receipt.items.reduce((s, it) => s + (it.discountAmount ?? 0), 0)

  const pays = on(opts.showPayment)
    ? receipt.payments.map((p) => line(L.methods[p.method] ?? p.method, m(p.amount))).join('')
    : ''

  const logo =
    on(opts.showLogo) && receipt.businessLogoUrl
      ? `<div class="logo"><img src="${escapeHtml(receipt.businessLogoUrl)}" alt=""/></div>`
      : ''
  const head = `
    <div class="ctr">
      ${logo}
      <div class="biz">${escapeHtml(receipt.businessName)}</div>
      ${receipt.businessAddress ? `<div class="muted">${escapeHtml(receipt.businessAddress)}</div>` : ''}
      ${receipt.businessPhone ? `<div class="muted">Tél : ${escapeHtml(receipt.businessPhone)}</div>` : ''}
      ${on(opts.showNiu) && receipt.businessNiu ? `<div class="muted">NIU : ${escapeHtml(receipt.businessNiu)}</div>` : ''}
    </div>`

  const qr =
    on(opts.showQr) && opts.qrImage
      ? `<div class="ctr"><img class="qr" src="${escapeHtml(opts.qrImage)}" alt=""/></div>`
      : ''
  const thanks =
    on(opts.showThanks) && (receipt.footer || L.thankYou)
      ? `<div class="ctr thanks">${escapeHtml(receipt.footer || L.thankYou)}</div>`
      : ''

  const body = `
    ${head}
    <div class="hr"></div>
    ${line('Reçu', receipt.saleNumber, 'b')}
    ${line(date, time)}
    ${on(opts.showCashier) && receipt.cashierName ? line(L.cashier, receipt.cashierName) : ''}
    ${receipt.customerName ? line(L.customer, receipt.customerName) : ''}
    <div class="hr"></div>
    <div class="it">${items}</div>
    <div class="hr"></div>
    ${totalDiscounts > 0 ? line(L.discounts, `- ${m(totalDiscounts)}`, 'muted') : ''}
    ${receipt.chargesAmount > 0 ? line(L.charges, `+ ${m(receipt.chargesAmount)}`, 'muted') : ''}
    ${line(L.total.toUpperCase(), `${m(receipt.totalAmount)}`, 'tot')}
    ${pays}
    ${receipt.creditAmount > 0 ? line(L.credit, m(receipt.creditAmount)) : ''}
    ${receipt.changeGiven > 0 ? line(L.change, m(receipt.changeGiven)) : ''}
    ${qr || thanks ? '<div class="hr"></div>' : ''}
    ${qr}
    ${thanks}
  `

  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(receipt.saleNumber)}</title><style>
    *{margin:0;padding:0;box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}
    html,body{background:#fff}
    body{font:12.5px/1.5 ui-sans-serif,system-ui,'Segoe UI',Roboto,Arial,sans-serif;color:#111;width:${width}mm;padding:14mm 5mm}
    .ctr{text-align:center}
    .logo{margin-bottom:6px}
    .logo img{max-width:46px;max-height:46px;object-fit:contain}
    .biz{font-size:15px;font-weight:800;letter-spacing:-.2px}
    .muted{font-size:11px;color:#555;margin-top:2px}
    .hr{border-top:1px dashed #b7b7b7;margin:7px 0}
    .line{display:flex;justify-content:space-between;gap:10px;margin:2px 0}
    .line .nm{flex:1;min-width:0}
    .line.b{font-weight:700}
    .line.muted span{color:#555}
    .it .sub{font-size:10.5px;color:#777;margin:-1px 0 3px}
    .line.tot{font-size:15px;font-weight:800;border-top:2px solid #111;margin-top:5px;padding-top:5px}
    .qr{width:88px;height:88px;margin:6px auto 0;display:block}
    .thanks{margin-top:10px;font-size:11.5px;color:#333}
    @media print{@page{margin:0}}
  </style></head><body>${body}</body></html>`
}

function formatQty(n: number, locale: string): string {
  try {
    return new Intl.NumberFormat(locale).format(n)
  } catch {
    return String(n)
  }
}
