import { contextBridge, ipcRenderer } from 'electron'
import { IPC, type BridgeApi } from '../shared/ipc'

// The ONLY surface the renderer can touch. No db, no tokens — just typed,
// high-level domain calls that resolve in the main-process services (the BFF).
const api: BridgeApi = {
  skeleton: {
    getCheck: () => ipcRenderer.invoke(IPC.skeletonCheck),
    getHealth: () => ipcRenderer.invoke(IPC.skeletonHealth),
  },
  theme: {
    set: (theme) => ipcRenderer.send(IPC.themeSet, theme),
  },
  window: {
    setTitleBarOverlay: (colors) => ipcRenderer.send(IPC.titlebarSetOverlay, colors),
  },
  auth: {
    getSession: () => ipcRenderer.invoke(IPC.authGetSession),
    login: (identifier, password) => ipcRenderer.invoke(IPC.authLogin, identifier, password),
    requestLogin: (identifier, channel) => ipcRenderer.invoke(IPC.authRequestLogin, identifier, channel),
    loginOtp: (identifier, code) => ipcRenderer.invoke(IPC.authLoginOtp, identifier, code),
    verifyPhone: (phone, code) => ipcRenderer.invoke(IPC.authVerifyPhone, phone, code),
    verifyEmail: (email, code) => ipcRenderer.invoke(IPC.authVerifyEmail, email, code),
    resendOtp: (identifier, type, channel) => ipcRenderer.invoke(IPC.authResendOtp, identifier, type, channel),
    register: (payload) => ipcRenderer.invoke(IPC.authRegister, payload),
    setupBusiness: (payload) => ipcRenderer.invoke(IPC.authSetupBusiness, payload),
    listPlans: () => ipcRenderer.invoke(IPC.authListPlans),
    selectPlan: (plan, billingCycle) => ipcRenderer.invoke(IPC.authSelectPlan, plan, billingCycle),
    selectBusiness: (businessId) => ipcRenderer.invoke(IPC.authSelectBusiness, businessId),
    listBusinesses: () => ipcRenderer.invoke(IPC.authListBusinesses),
    offlineLogin: (password) => ipcRenderer.invoke(IPC.authOfflineLogin, password),
    logout: () => ipcRenderer.invoke(IPC.authLogout),
  },
  sync: {
    trigger: () => ipcRenderer.invoke(IPC.syncTrigger),
    retry: () => ipcRenderer.invoke(IPC.syncRetry),
    getStatus: () => ipcRenderer.invoke(IPC.syncGetStatus),
    onStatus: (cb) => {
      const listener = (_e: unknown, status: Parameters<typeof cb>[0]) => cb(status)
      ipcRenderer.on(IPC.syncStatusEvent, listener)
      return () => ipcRenderer.removeListener(IPC.syncStatusEvent, listener)
    },
  },
  categories: {
    list: (query) => ipcRenderer.invoke(IPC.categoriesList, query),
    listAll: () => ipcRenderer.invoke(IPC.categoriesListAll),
    listSelectable: (query) => ipcRenderer.invoke(IPC.categoriesSelectable, query),
    listParentOptions: (query) => ipcRenderer.invoke(IPC.categoriesParentOptions, query),
    create: (input) => ipcRenderer.invoke(IPC.categoriesCreate, input),
    update: (id, input) => ipcRenderer.invoke(IPC.categoriesUpdate, id, input),
    remove: (id) => ipcRenderer.invoke(IPC.categoriesDelete, id),
  },
  attributes: {
    listGroups: (query) => ipcRenderer.invoke(IPC.attributesListGroups, query),
    listAllGroups: () => ipcRenderer.invoke(IPC.attributesListAllGroups),
    createGroup: (input) => ipcRenderer.invoke(IPC.attributesCreateGroup, input),
    updateGroup: (id, input) => ipcRenderer.invoke(IPC.attributesUpdateGroup, id, input),
    deleteGroup: (id) => ipcRenderer.invoke(IPC.attributesDeleteGroup, id),
    addOption: (groupId, input) => ipcRenderer.invoke(IPC.attributesAddOption, groupId, input),
    updateOption: (optionId, input) => ipcRenderer.invoke(IPC.attributesUpdateOption, optionId, input),
    deleteOption: (optionId) => ipcRenderer.invoke(IPC.attributesDeleteOption, optionId),
    listCategoryLinks: (categoryId) => ipcRenderer.invoke(IPC.attributesListCategoryLinks, categoryId),
    setCategoryLinks: (categoryId, links) => ipcRenderer.invoke(IPC.attributesSetCategoryLinks, categoryId, links),
  },
  units: {
    list: (query) => ipcRenderer.invoke(IPC.unitsList, query),
    create: (input) => ipcRenderer.invoke(IPC.unitsCreate, input),
    update: (id, input) => ipcRenderer.invoke(IPC.unitsUpdate, id, input),
    remove: (id) => ipcRenderer.invoke(IPC.unitsDelete, id),
  },
  brands: {
    list: (query) => ipcRenderer.invoke(IPC.brandsList, query),
    get: (id) => ipcRenderer.invoke(IPC.brandsGet, id),
    create: (input) => ipcRenderer.invoke(IPC.brandsCreate, input),
    update: (id, input) => ipcRenderer.invoke(IPC.brandsUpdate, id, input),
    remove: (id) => ipcRenderer.invoke(IPC.brandsDelete, id),
    addModel: (brandId, input) => ipcRenderer.invoke(IPC.brandsAddModel, brandId, input),
    updateModel: (modelId, input) => ipcRenderer.invoke(IPC.brandsUpdateModel, modelId, input),
    removeModel: (modelId) => ipcRenderer.invoke(IPC.brandsDeleteModel, modelId),
  },
  products: {
    list: (query) => ipcRenderer.invoke(IPC.productsList, query),
    stats: () => ipcRenderer.invoke(IPC.productsStats),
    get: (id) => ipcRenderer.invoke(IPC.productsGet, id),
    create: (input) => ipcRenderer.invoke(IPC.productsCreate, input),
    update: (id, input) => ipcRenderer.invoke(IPC.productsUpdate, id, input),
    remove: (id) => ipcRenderer.invoke(IPC.productsDelete, id),
    listImages: (productId) => ipcRenderer.invoke(IPC.productsListImages, productId),
    setImages: (productId, images) => ipcRenderer.invoke(IPC.productsSetImages, productId, images),
    listVariants: (productId) => ipcRenderer.invoke(IPC.productsListVariants, productId),
    setVariants: (productId, variants) => ipcRenderer.invoke(IPC.productsSetVariants, productId, variants),
    addVariant: (productId, input) => ipcRenderer.invoke(IPC.productsAddVariant, productId, input),
    updateVariant: (productId, variantId, input) => ipcRenderer.invoke(IPC.productsUpdateVariant, productId, variantId, input),
    removeVariant: (productId, variantId, reason) => ipcRenderer.invoke(IPC.productsRemoveVariant, productId, variantId, reason),
    listSerialUnits: (productId) => ipcRenderer.invoke(IPC.productsListSerialUnits, productId),
    listInStockSerials: (productId, variantId, search) => ipcRenderer.invoke(IPC.productsListInStockSerials, productId, variantId, search),
    resolveScan: (code) => ipcRenderer.invoke(IPC.productsResolveScan, code),
    setSerialUnits: (productId, units) => ipcRenderer.invoke(IPC.productsSetSerialUnits, productId, units),
    addSerialUnits: (productId, units, notes) => ipcRenderer.invoke(IPC.productsAddSerialUnits, productId, units, notes),
    retireSerialUnit: (productId, unitId, reason) => ipcRenderer.invoke(IPC.productsRetireSerialUnit, productId, unitId, reason),
    updateSerialNumber: (productId, unitId, serialNumber) =>
      ipcRenderer.invoke(IPC.productsUpdateSerialNumber, productId, unitId, serialNumber),
    listMovements: (productId) => ipcRenderer.invoke(IPC.productsListMovements, productId),
  },
  inventory: {
    list: (query) => ipcRenderer.invoke(IPC.inventoryList, query),
    stats: () => ipcRenderer.invoke(IPC.inventoryStats),
    reorderSuggestions: () => ipcRenderer.invoke(IPC.inventoryReorderSuggestions),
    restock: (input) => ipcRenderer.invoke(IPC.inventoryRestock, input),
    adjust: (productId, input) => ipcRenderer.invoke(IPC.inventoryAdjust, productId, input),
    setThreshold: (productId, input) => ipcRenderer.invoke(IPC.inventorySetThreshold, productId, input),
    listMovements: (productId, query) => ipcRenderer.invoke(IPC.inventoryListMovements, productId, query),
  },
  contacts: {
    list: (query) => ipcRenderer.invoke(IPC.contactsList, query),
    summary: () => ipcRenderer.invoke(IPC.contactsSummary),
    listAllSuppliers: () => ipcRenderer.invoke(IPC.contactsListAllSuppliers),
    listAllCustomers: () => ipcRenderer.invoke(IPC.contactsListAllCustomers),
    get: (id) => ipcRenderer.invoke(IPC.contactsGet, id),
    create: (input) => ipcRenderer.invoke(IPC.contactsCreate, input),
    update: (id, input) => ipcRenderer.invoke(IPC.contactsUpdate, id, input),
    remove: (id) => ipcRenderer.invoke(IPC.contactsDelete, id),
  },
  debts: {
    listByContact: (contactId, query) => ipcRenderer.invoke(IPC.debtsListByContact, contactId, query),
    statement: (contactId, direction) => ipcRenderer.invoke(IPC.debtsStatement, contactId, direction),
    recordPayment: (debtId, input) => ipcRenderer.invoke(IPC.debtsRecordPayment, debtId, input),
    offset: (contactId) => ipcRenderer.invoke(IPC.debtsOffset, contactId),
  },
  expenses: {
    list: (query) => ipcRenderer.invoke(IPC.expensesList, query),
    get: (id) => ipcRenderer.invoke(IPC.expensesGet, id),
    summary: (query) => ipcRenderer.invoke(IPC.expensesSummary, query),
    trend: () => ipcRenderer.invoke(IPC.expensesTrend),
    create: (input) => ipcRenderer.invoke(IPC.expensesCreate, input),
    update: (id, input) => ipcRenderer.invoke(IPC.expensesUpdate, id, input),
    setStatus: (id, status, paymentMethod) => ipcRenderer.invoke(IPC.expensesSetStatus, id, status, paymentMethod),
    remove: (id) => ipcRenderer.invoke(IPC.expensesRemove, id),
  },
  expenseCategories: {
    listAll: () => ipcRenderer.invoke(IPC.expenseCategoriesListAll),
    create: (input) => ipcRenderer.invoke(IPC.expenseCategoriesCreate, input),
  },
  openingBalances: {
    upsert: (input) => ipcRenderer.invoke(IPC.openingBalancesUpsert, input),
    listForContact: (contactId) => ipcRenderer.invoke(IPC.openingBalancesListForContact, contactId),
  },
  rfqs: {
    list: (query) => ipcRenderer.invoke(IPC.rfqList, query),
    get: (id) => ipcRenderer.invoke(IPC.rfqGet, id),
    create: (input) => ipcRenderer.invoke(IPC.rfqCreate, input),
    recordQuote: (rfqId, input) => ipcRenderer.invoke(IPC.rfqRecordQuote, rfqId, input),
    buildDocument: (rfqId, supplierId) => ipcRenderer.invoke(IPC.rfqBuildDocument, rfqId, supplierId),
    send: (rfqId, supplierId, channel) => ipcRenderer.invoke(IPC.rfqSend, rfqId, supplierId, channel),
  },
  purchaseOrders: {
    list: (query) => ipcRenderer.invoke(IPC.poList, query),
    get: (id) => ipcRenderer.invoke(IPC.poGet, id),
    create: (input) => ipcRenderer.invoke(IPC.poCreate, input),
    createFromRfq: (rfqId, input) => ipcRenderer.invoke(IPC.poCreateFromRfq, rfqId, input),
    buildDocument: (poId) => ipcRenderer.invoke(IPC.poBuildDocument, poId),
    send: (poId, channel) => ipcRenderer.invoke(IPC.poSend, poId, channel),
    cancel: (poId) => ipcRenderer.invoke(IPC.poCancel, poId),
  },
  documents: {
    send: (input) => ipcRenderer.invoke(IPC.documentsSend, input),
    downloadPdf: (input) => ipcRenderer.invoke(IPC.documentsDownload, input),
    downloadHtmlPdf: (html, filename) => ipcRenderer.invoke(IPC.documentsDownloadHtml, html, filename),
    shareHtmlPdf: (input) => ipcRenderer.invoke(IPC.documentsShareHtml, input),
  },
  audit: {
    list: (query) => ipcRenderer.invoke(IPC.auditList, query),
  },
  uploads: {
    file: (input) => ipcRenderer.invoke(IPC.uploadsFile, input),
  },
  charges: {
    listActive: () => ipcRenderer.invoke(IPC.chargesListActive),
  },
  sales: {
    create: (input) => ipcRenderer.invoke(IPC.salesCreate, input),
    list: (query) => ipcRenderer.invoke(IPC.salesList, query),
    listAll: (query) => ipcRenderer.invoke(IPC.salesListAll, query),
    summary: (query) => ipcRenderer.invoke(IPC.salesSummary, query),
    get: (id) => ipcRenderer.invoke(IPC.salesGet, id),
    sendReceipt: (saleId, channel, locale, opts) => ipcRenderer.invoke(IPC.salesSendReceipt, saleId, channel, locale, opts),
    printReceipt: (saleId, locale) => ipcRenderer.invoke(IPC.salesPrintReceipt, saleId, locale),
    downloadReceipt: (saleId, locale) => ipcRenderer.invoke(IPC.salesDownloadReceipt, saleId, locale),
    receiptHtml: (saleId, locale) => ipcRenderer.invoke(IPC.salesReceiptHtml, saleId, locale),
  },
  savings: {
    getForCustomer: (customerId) => ipcRenderer.invoke(IPC.savingsGetForCustomer, customerId),
  },
  deposits: {
    list: (query) => ipcRenderer.invoke(IPC.depositsList, query),
    get: (id) => ipcRenderer.invoke(IPC.depositsGet, id),
    statement: (id) => ipcRenderer.invoke(IPC.depositsStatement, id),
    summary: () => ipcRenderer.invoke(IPC.depositsSummary),
    create: (input) => ipcRenderer.invoke(IPC.depositsCreate, input),
    addPayment: (id, input) => ipcRenderer.invoke(IPC.depositsAddPayment, id, input),
    close: (id, input) => ipcRenderer.invoke(IPC.depositsClose, id, input),
    receiptHtml: (transactionId, locale) => ipcRenderer.invoke(IPC.depositsReceiptHtml, transactionId, locale),
    printReceipt: (transactionId, locale) => ipcRenderer.invoke(IPC.depositsPrintReceipt, transactionId, locale),
    downloadReceipt: (transactionId, locale) => ipcRenderer.invoke(IPC.depositsDownloadReceipt, transactionId, locale),
    sendReceipt: (transactionId, channel, locale, opts) => ipcRenderer.invoke(IPC.depositsSendReceipt, transactionId, channel, locale, opts),
  },
}

contextBridge.exposeInMainWorld('api', api)
