import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1775292485376 implements MigrationInterface {
    name = 'InitSchema1775292485376'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "token_id" character varying NOT NULL, "token_hash" character varying NOT NULL, "family_id" character varying NOT NULL, "user_id" uuid NOT NULL, "device_id" character varying, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "revoked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unq_refresh_tokens_token_id" ON "refresh_tokens" ("token_id") `);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "business_id" uuid NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_product_categories_business_id_deleted_at" ON "product_categories" ("business_id", "deleted_at") `);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "business_id" uuid NOT NULL, "cashier_id" uuid NOT NULL, "device_id" character varying, "total_amount" numeric(12,2) NOT NULL, "discount_amount" numeric(12,2) NOT NULL DEFAULT '0', "tax_amount" numeric(12,2) NOT NULL DEFAULT '0', "net_amount" numeric(12,2) NOT NULL, "payment_method" character varying NOT NULL, "momo_reference" character varying, "notes" character varying, "receipt_number" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'COMPLETED', CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sales_business_id_created_at" ON "sales" ("business_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_sales_business_id_deleted_at" ON "sales" ("business_id", "deleted_at") `);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "sale_id" uuid NOT NULL, "product_id" uuid NOT NULL, "product_name" character varying NOT NULL, "quantity" numeric(10,3) NOT NULL, "unit_price" numeric(12,2) NOT NULL, "total_price" numeric(12,2) NOT NULL, CONSTRAINT "PK_5a7dc5b4562a9e590528b3e08ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sale_items_product_id" ON "sale_items" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sale_items_sale_id" ON "sale_items" ("sale_id") `);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "business_id" uuid NOT NULL, "product_id" uuid NOT NULL, "type" character varying NOT NULL, "quantity" numeric(10,3) NOT NULL, "previous_quantity" numeric(10,3) NOT NULL, "new_quantity" numeric(10,3) NOT NULL, "reason" character varying, "reference_id" character varying, "recorded_by_id" uuid NOT NULL, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_stock_movements_business_id_product_id" ON "stock_movements" ("business_id", "product_id") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "business_id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "sku" character varying, "barcode" character varying, "price" numeric(12,2) NOT NULL, "cost_price" numeric(12,2), "stock_quantity" integer NOT NULL DEFAULT '0', "low_stock_threshold" integer NOT NULL DEFAULT '5', "unit" character varying NOT NULL DEFAULT 'piece', "category_id" uuid, "image_url" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "unq_products_business_id_sku" UNIQUE ("business_id", "sku"), CONSTRAINT "unq_products_business_id_barcode" UNIQUE ("business_id", "barcode"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_products_business_id_deleted_at" ON "products" ("business_id", "deleted_at") `);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "business_id" uuid NOT NULL, "recorded_by_id" uuid NOT NULL, "category" character varying NOT NULL, "description" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "payment_method" character varying NOT NULL, "receipt_url" character varying, "date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_expenses_business_id_date" ON "expenses" ("business_id", "date") `);
        await queryRunner.query(`CREATE INDEX "idx_expenses_business_id_deleted_at" ON "expenses" ("business_id", "deleted_at") `);
        await queryRunner.query(`CREATE TABLE "sync_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "business_id" uuid NOT NULL, "device_id" character varying NOT NULL, "pushed_count" integer NOT NULL DEFAULT '0', "pulled_count" integer NOT NULL DEFAULT '0', "conflict_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_f441fe15484e077c80ddec89336" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sync_logs_business_id_device_id" ON "sync_logs" ("business_id", "device_id") `);
        await queryRunner.query(`CREATE TABLE "business_overrides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "business_id" uuid NOT NULL, "resource" character varying NOT NULL, "granted" boolean NOT NULL DEFAULT true, "granted_by" character varying NOT NULL, "reason" character varying NOT NULL, "granted_at" TIMESTAMP NOT NULL, "expires_at" TIMESTAMP, CONSTRAINT "PK_eaa956ec94535dc5e6290b5f507" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_business_overrides_expires_at" ON "business_overrides" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_business_overrides_business_id" ON "business_overrides" ("business_id") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_events_event_enum" AS ENUM('TRIAL_STARTED', 'TRIAL_ENDING_SOON', 'TRIAL_ENDED', 'PLAN_SELECTED', 'PLAN_UPGRADED', 'PLAN_DOWNGRADED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'CANCELLED', 'REACTIVATED', 'OVERRIDE_GRANTED', 'OVERRIDE_REVOKED')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_events_from_plan_enum" AS ENUM('FREE', 'SOLO', 'BUSINESS', 'PRO')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_events_to_plan_enum" AS ENUM('FREE', 'SOLO', 'BUSINESS', 'PRO')`);
        await queryRunner.query(`CREATE TABLE "subscription_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "business_id" uuid NOT NULL, "event" "public"."subscription_events_event_enum" NOT NULL, "from_plan" "public"."subscription_events_from_plan_enum", "to_plan" "public"."subscription_events_to_plan_enum", "metadata" jsonb, CONSTRAINT "PK_7eb5647aa3071cffad0124bceee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_subscription_events_business_id" ON "subscription_events" ("business_id") `);
        await queryRunner.query(`CREATE TYPE "public"."businesses_type_enum" AS ENUM('EPICERIE', 'BOUTIQUE', 'RESTAURANT', 'PHARMACIE', 'SALON', 'ELECTRONIQUE', 'AUTRE')`);
        await queryRunner.query(`CREATE TYPE "public"."businesses_plan_enum" AS ENUM('FREE', 'SOLO', 'BUSINESS', 'PRO')`);
        await queryRunner.query(`CREATE TYPE "public"."businesses_subscription_status_enum" AS ENUM('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, "phone" character varying, "email" character varying, "address" character varying, "city" character varying, "country" character varying NOT NULL DEFAULT 'CM', "type" "public"."businesses_type_enum" NOT NULL DEFAULT 'AUTRE', "currency" character varying NOT NULL DEFAULT 'XAF', "logo_url" character varying, "owner_id" uuid NOT NULL, "plan" "public"."businesses_plan_enum" NOT NULL DEFAULT 'FREE', "subscription_status" "public"."businesses_subscription_status_enum" NOT NULL DEFAULT 'TRIAL', "trial_started_at" TIMESTAMP, "trial_ends_at" TIMESTAMP, "current_period_start" TIMESTAMP, "current_period_end" TIMESTAMP, "cancel_at_period_end" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_8881b96819252080592fe1592e" UNIQUE ("owner_id"), CONSTRAINT "PK_bc1bf63498dd2368ce3dc8686e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unq_businesses_owner_id" ON "businesses" ("owner_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unq_businesses_slug" ON "businesses" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('OWNER', 'MANAGER', 'CASHIER', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('PENDING', 'PHONE_VERIFIED', 'ACTIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."users_onboarding_step_enum" AS ENUM('VERIFY_PHONE', 'VERIFY_EMAIL', 'SELECT_PLAN', 'SETUP_BUSINESS', 'ADD_FIRST_PRODUCT', 'COMPLETE')`);
        await queryRunner.query(`CREATE TYPE "public"."users_preferred_phone_channel_enum" AS ENUM('SMS', 'WHATSAPP')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "email" character varying(255), "phone" character varying NOT NULL, "name" character varying NOT NULL, "password_hash" character varying, "avatar_url" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'OWNER', "language" character varying NOT NULL DEFAULT 'fr', "is_email_verified" boolean NOT NULL DEFAULT false, "is_phone_verified" boolean NOT NULL DEFAULT false, "status" "public"."users_status_enum" NOT NULL DEFAULT 'PENDING', "onboarding_step" "public"."users_onboarding_step_enum" NOT NULL DEFAULT 'VERIFY_PHONE', "failed_login_attempts" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP WITH TIME ZONE, "preferred_phone_channel" "public"."users_preferred_phone_channel_enum" NOT NULL DEFAULT 'SMS', "is_active" boolean NOT NULL DEFAULT true, "business_id" uuid, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unq_users_phone" ON "users" ("phone") WHERE phone IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unq_users_email" ON "users" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."verification_codes_channel_enum" AS ENUM('PHONE', 'EMAIL')`);
        await queryRunner.query(`CREATE TYPE "public"."verification_codes_purpose_enum" AS ENUM('REGISTER', 'LOGIN', 'VERIFY_PHONE', 'VERIFY_EMAIL')`);
        await queryRunner.query(`CREATE TABLE "verification_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "channel" "public"."verification_codes_channel_enum" NOT NULL, "purpose" "public"."verification_codes_purpose_enum" NOT NULL, "code_hash" character varying NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_18741b6b8bf1680dbf5057421d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_verification_codes_channel_purpose" ON "verification_codes" ("channel", "purpose") `);
        await queryRunner.query(`CREATE INDEX "idx_verification_codes_user_id" ON "verification_codes" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."plan_configs_plan_enum" AS ENUM('FREE', 'SOLO', 'BUSINESS', 'PRO')`);
        await queryRunner.query(`CREATE TABLE "plan_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "plan" "public"."plan_configs_plan_enum" NOT NULL, "resources" text array NOT NULL, "display_name" character varying NOT NULL, "price_xaf" integer NOT NULL, "updated_by" character varying NOT NULL, CONSTRAINT "PK_88aaab02bdd6a1a716936a1c0ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "unq_plan_configs_plan" ON "plan_configs" ("plan") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "fk_product_categories_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "fk_sales_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "fk_sales_cashier_id" FOREIGN KEY ("cashier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "fk_sale_items_sale_id" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "fk_sale_items_product_id" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "fk_stock_movements_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "fk_stock_movements_product_id" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "fk_stock_movements_recorded_by_id" FOREIGN KEY ("recorded_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "fk_products_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "fk_products_category_id" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "fk_expenses_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "fk_expenses_recorded_by_id" FOREIGN KEY ("recorded_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_logs" ADD CONSTRAINT "fk_sync_logs_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_overrides" ADD CONSTRAINT "fk_business_overrides_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_events" ADD CONSTRAINT "fk_subscription_events_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "fk_businesses_owner_id" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "fk_users_business_id" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_codes" ADD CONSTRAINT "fk_verification_codes_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "verification_codes" DROP CONSTRAINT "fk_verification_codes_user_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "fk_users_business_id"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "fk_businesses_owner_id"`);
        await queryRunner.query(`ALTER TABLE "subscription_events" DROP CONSTRAINT "fk_subscription_events_business_id"`);
        await queryRunner.query(`ALTER TABLE "business_overrides" DROP CONSTRAINT "fk_business_overrides_business_id"`);
        await queryRunner.query(`ALTER TABLE "sync_logs" DROP CONSTRAINT "fk_sync_logs_business_id"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "fk_expenses_recorded_by_id"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "fk_expenses_business_id"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "fk_products_category_id"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "fk_products_business_id"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "fk_stock_movements_recorded_by_id"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "fk_stock_movements_product_id"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "fk_stock_movements_business_id"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "fk_sale_items_product_id"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "fk_sale_items_sale_id"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "fk_sales_cashier_id"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "fk_sales_business_id"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "fk_product_categories_business_id"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "fk_refresh_tokens_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."unq_plan_configs_plan"`);
        await queryRunner.query(`DROP TABLE "plan_configs"`);
        await queryRunner.query(`DROP TYPE "public"."plan_configs_plan_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_verification_codes_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_verification_codes_channel_purpose"`);
        await queryRunner.query(`DROP TABLE "verification_codes"`);
        await queryRunner.query(`DROP TYPE "public"."verification_codes_purpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."verification_codes_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."unq_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."unq_users_phone"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_preferred_phone_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_onboarding_step_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."unq_businesses_slug"`);
        await queryRunner.query(`DROP INDEX "public"."unq_businesses_owner_id"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_subscription_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_plan_enum"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_subscription_events_business_id"`);
        await queryRunner.query(`DROP TABLE "subscription_events"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_events_to_plan_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_events_from_plan_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_events_event_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_business_overrides_business_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_business_overrides_expires_at"`);
        await queryRunner.query(`DROP TABLE "business_overrides"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sync_logs_business_id_device_id"`);
        await queryRunner.query(`DROP TABLE "sync_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expenses_business_id_deleted_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expenses_business_id_date"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_business_id_deleted_at"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stock_movements_business_id_product_id"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sale_items_sale_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sale_items_product_id"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_business_id_deleted_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sales_business_id_created_at"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_categories_business_id_deleted_at"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP INDEX "public"."unq_refresh_tokens_token_id"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
    }

}
