import { SubscriptionPlan } from "./business.types"

export enum Resource {
  SALES_CREATE = 'SALES_CREATE',
  SALES_VIEW = 'SALES_VIEW',
  SALES_VOID = 'SALES_VOID',
  SALES_EXPORT = 'SALES_EXPORT',

  PRODUCTS_CREATE = 'PRODUCTS_CREATE',
  PRODUCTS_VIEW = 'PRODUCTS_VIEW',
  PRODUCTS_EDIT = 'PRODUCTS_EDIT',
  PRODUCTS_DELETE = 'PRODUCTS_DELETE',
  PRODUCTS_LIMIT_50 = 'PRODUCTS_LIMIT_50',
  PRODUCTS_UNLIMITED = 'PRODUCTS_UNLIMITED',
  PRODUCTS_IMPORT_CSV = 'PRODUCTS_IMPORT_CSV',

  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_ADJUST = 'INVENTORY_ADJUST',
  INVENTORY_ALERTS = 'INVENTORY_ALERTS',

  EXPENSES_CREATE = 'EXPENSES_CREATE',
  EXPENSES_VIEW = 'EXPENSES_VIEW',
  EXPENSES_EDIT = 'EXPENSES_EDIT',
  EXPENSES_DELETE = 'EXPENSES_DELETE',
  EXPENSES_CATEGORIES = 'EXPENSES_CATEGORIES',

  CONTACTS_VIEW = 'CONTACTS_VIEW',
  CONTACTS_MANAGE = 'CONTACTS_MANAGE',
  DEBTS_VIEW = 'DEBTS_VIEW',
  DEBTS_RECORD_PAYMENT = 'DEBTS_RECORD_PAYMENT',
  DEBTS_DELETE_PAYMENT = 'DEBTS_DELETE_PAYMENT',
  DEBTS_WRITE_OFF = 'DEBTS_WRITE_OFF',

  REPORTS_DAILY = 'REPORTS_DAILY',
  REPORTS_WEEKLY = 'REPORTS_WEEKLY',
  REPORTS_MONTHLY = 'REPORTS_MONTHLY',
  REPORTS_EXPORT_PDF = 'REPORTS_EXPORT_PDF',
  REPORTS_EXPORT_CSV = 'REPORTS_EXPORT_CSV',

  RECEIPTS_GENERATE = 'RECEIPTS_GENERATE',
  RECEIPTS_WHATSAPP = 'RECEIPTS_WHATSAPP',

  SCANNER_CAMERA = 'SCANNER_CAMERA',
  SCANNER_USB = 'SCANNER_USB',

  DESKTOP_ACCESS = 'DESKTOP_ACCESS',

  STAFF_INVITE = 'STAFF_INVITE',
  STAFF_MANAGE = 'STAFF_MANAGE',
  STAFF_LIMIT_3 = 'STAFF_LIMIT_3',
  STAFF_UNLIMITED = 'STAFF_UNLIMITED',

  BRANCHES_MULTI = 'BRANCHES_MULTI',
  BRANCHES_DASHBOARD = 'BRANCHES_DASHBOARD',
  BRANCHES_REPORTS = 'BRANCHES_REPORTS',

  API_ACCESS = 'API_ACCESS',
}

export const FREE_PERMISSIONS: Resource[] = [
  Resource.SALES_CREATE,
  Resource.SALES_VIEW,
  Resource.PRODUCTS_CREATE,
  Resource.PRODUCTS_VIEW,
  Resource.PRODUCTS_EDIT,
  Resource.PRODUCTS_DELETE,
  Resource.PRODUCTS_LIMIT_50,
  Resource.INVENTORY_VIEW,
  Resource.INVENTORY_ADJUST,
  Resource.INVENTORY_ALERTS,
  Resource.EXPENSES_CREATE,
  Resource.EXPENSES_VIEW,
  Resource.EXPENSES_EDIT,
  Resource.EXPENSES_DELETE,
  Resource.CONTACTS_VIEW,
  Resource.CONTACTS_MANAGE,
  Resource.DEBTS_VIEW,
  Resource.DEBTS_RECORD_PAYMENT,
  Resource.DEBTS_DELETE_PAYMENT,
  Resource.DEBTS_WRITE_OFF,
  Resource.REPORTS_DAILY,
  Resource.RECEIPTS_GENERATE,
  Resource.RECEIPTS_WHATSAPP,
]

export interface SpecialPermission {
  resource: Resource
  grantedAt: number
  expiresAt: number | null
  grantedBy: string
  reason: string
  isRevocation: boolean
}

export interface AuthPermissions {
  plan: SubscriptionPlan | null
  effectivePermissions: Resource[]
  specialPermissions: SpecialPermission[]
  permissionsIssuedAt: number
  permissionsExpiresAt: number
}
